.SUFFIXES: 

QEMUFLAGS  := -m 2G -chardev file,id=dbg,path=debugcon.log
QEMUCORES  := 4
override IMAGE_NAME := Synx-x86_64
override OUTPUT := sxImage

CXX       = g++
LD        = ld
OBJCOPY   = objcopy
CXXFLAGS := -g -O2 -pipe
CPPFLAGS :=
LDFLAGS  :=
QUIET     = 1
DEBUG     = 
GDB       =
DEBUGCON  = 

ifeq ($(shell ! $(CXX) --version 2>/dev/null | grep -q '^Target: '; echo $$?),1)
	override CXX += -target x86_64-unknown-none-elf
endif
ifneq ($(QUIET),)
	override Q = @
else
	override Q=
endif
ifneq ($(DEBUG),)
	override QEMUFLAGS += -d int,cpu_reset
endif
ifneq ($(GDB),)
	override QEMUFLAGS += -s -S
endif

override CXXFLAGS += \
	-Wall -Wextra -std=c++11 \
	-nodefaultlibs -nostartfiles -nostdlib -nostdinc -nostdinc++ \
	-ffreestanding \
	-fno-omit-frame-pointer -fno-stack-protector -fno-stack-check \
	-fno-lto -fno-PIC -ffunction-sections -fdata-sections \
	-fno-exceptions -fno-rtti \
	-m64 -march=x86-64 -mabi=sysv \
	-mno-80387 -mno-sse -mno-sse2 -mno-mmx -mno-avx -msoft-float \
	-mno-red-zone -mcmodel=kernel

override CPPFLAGS := \
	-I include -isystem klibc \
	$(CPPFLAGS) -MMD -MP

override LDFLAGS += \
	-m elf_x86_64 -static \
	-z max-page-size=0x1000 \
	--gc-sections \
	-T SynxKernel-x86_64.lds

override CXXFILES    := $(wildcard */*.cpp)
override ASFILES     := $(wildcard */*.S)
override CXXOBJECTS  := $(patsubst %.cpp, build/obj/%.cpp.o, $(CXXFILES))
override ASOBJECTS   := $(patsubst %.S, build/obj/%.S.o, $(ASFILES))
override HEADER_DEPS := $(patsubst %.cpp, build/obj/%.cpp.d, $(CXXFILES))
override HEADER_DEPS += $(patsubst %.S, build/obj/%.S.d, $(ASFILES))

KALLSYMS_OBJ := build/obj/kallsyms/kallsyms.cpp.o
OTHER_OBJECTS := $(filter-out $(KALLSYMS_OBJ), $(CXXOBJECTS) $(ASOBJECTS))

-include $(HEADER_DEPS)


build/obj/src/%.cpp.o: src/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/kallsyms/%.cpp.o: kallsyms/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/mem/%.cpp.o: mem/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/proc/%.cpp.o: proc/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/proc/%.S.o: proc/%.S
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/bin/symtab.txt: build/bin/sxImage_temp.elf
	@echo "  NM      $<"
	$(Q)nm -n --defined-only $< | grep -E ' [Tt] ' > $@

build/bin/symtab_gen.cpp: build/bin/symtab.txt
	@echo "  GEN     $@"
	@echo "// Auto-generated by Makefile" > $@
	@echo "#include <stdint.h>" >> $@
	@echo "struct KSym { uint64_t addr; const char* name; };" >> $@
	@echo "extern \"C\" const KSym kallsyms_syms[] = {" >> $@
	@awk '{printf "    {0x%s, \"%s\"},\n", $$1, $$3}' $< >> $@
	@echo "    {0, nullptr}" >> $@
	@echo "};" >> $@
	@echo "extern \"C\" const uint64_t kallsyms_syms_count = $(shell wc -l < $<);" >> $@

build/bin/sxImage_temp.elf: $(OTHER_OBJECTS) build/obj/kallsyms/kallsyms_stub.cpp.o SynxKernel-x86_64.lds
	@mkdir -p "$(dir $@)"
	@echo "  LD      $@"
	$(Q)$(LD) $(LDFLAGS) $(OTHER_OBJECTS) build/obj/kallsyms/kallsyms_stub.cpp.o -o $@

build/bin/symtab.bin build/bin/strtab.bin: build/bin/sxImage_temp.elf
	@echo "  OBJCOPY "
	$(Q)$(OBJCOPY) -j .symtab -O binary $< build/bin/symtab.bin
	$(Q)$(OBJCOPY) -j .strtab -O binary $< build/bin/strtab.bin

build/bin/symtab.o: build/bin/symtab.bin
	@echo "  LD      $@"
	$(Q)$(LD) -r -b binary -o $@ $<

build/obj/build/bin/symtab_gen.o: build/bin/symtab_gen.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/bin/$(OUTPUT): $(OTHER_OBJECTS) $(KALLSYMS_OBJ) build/obj/build/bin/symtab_gen.o SynxKernel-x86_64.lds
	@mkdir -p "$(dir $@)"
	@echo "  LD$@"
	$(Q)$(LD) $(LDFLAGS) $(OTHER_OBJECTS) $(KALLSYMS_OBJ) build/obj/build/bin/symtab_gen.o -o $@


.PHONY: kernel
kernel: build/bin/$(OUTPUT)

.PHONY: bootloader
bootloader: 
	$(Q)make -C assets/limine-bootloader all

$(IMAGE_NAME).iso: kernel bootloader
	$(Q)mkdir -p build/iso_root/boot
	$(Q)cp -v build/bin/$(OUTPUT) build/iso_root/boot/
	$(Q)mkdir -p build/iso_root/boot/limine
	$(Q)cp -v limine.conf assets/limine-bootloader/limine-bios.sys assets/limine-bootloader/limine-bios-cd.bin assets/limine-bootloader/limine-uefi-cd.bin build/iso_root/boot/limine/
	$(Q)mkdir -p build/iso_root/EFI/BOOT
	$(Q)cp -v assets/limine-bootloader/BOOTX64.EFI build/iso_root/EFI/BOOT/
	$(Q)cp -v assets/limine-bootloader/BOOTIA32.EFI build/iso_root/EFI/BOOT/
	@echo "XORRISO $(IMAGE_NAME).iso"
	$(Q)xorriso -as mkisofs -R -r -J -b boot/limine/limine-bios-cd.bin \
		-no-emul-boot -boot-load-size 4 -boot-info-table -hfsplus \
		-apm-block-size 2048 --efi-boot boot/limine/limine-uefi-cd.bin \
		-efi-boot-part --efi-boot-image --protective-msdos-label \
		build/iso_root -o $(IMAGE_NAME).iso
	$(Q)./assets/limine-bootloader/limine bios-install $(IMAGE_NAME).iso

.PHONY: all
all: $(IMAGE_NAME).iso

.PHONY: run
run: all
	$(Q)qemu-system-x86_64 \
		-M q35 \
		-cdrom $(IMAGE_NAME).iso \
		-boot d \
		-smp $(QEMUCORES) \
		-no-reboot \
		$(QEMUFLAGS)

.PHONY: clean
clean:
	rm -rf build Synx-x86_64.iso
	make -C assets/limine-bootloader clean