.SUFFIXES: 

# ================= 基础配置 =================
QEMUFLAGS := -m 2G
override IMAGE_NAME := Synx-x86_64
override OUTPUT := sxImage

CXX       = g++
LD        = ld
OBJCOPY   = objcopy
CXXFLAGS := -g -O2 -pipe
CPPFLAGS :=
LDFLAGS  :=
Q         = @

# 交叉编译器检测
ifeq ($(shell ! $(CXX) --version 2>/dev/null | grep -q '^Target: '; echo $$?),1)
	override CXX += -target x86_64-unknown-none-elf
endif

# ================= 编译参数 =================
override CXXFLAGS += \
	-Wall -Wextra -std=c++11 \
	-nodefaultlibs -nostartfiles -nostdlib -nostdinc -nostdinc++ \
	-ffreestanding \
	-fno-omit-frame-pointer -fno-stack-protector -fno-stack-check \
	-fno-lto -fno-PIC -ffunction-sections -fdata-sections \
	-fno-exceptions -fno-rtti \
	-m64 -march=x86-64 -mabi=sysv \
	-mno-80387 -mno-mmx -mno-sse -mno-sse2 \
	-mno-red-zone -mcmodel=kernel

override CPPFLAGS := \
	-I include -isystem klibc \
	$(CPPFLAGS) -MMD -MP

override LDFLAGS += \
	-m elf_x86_64 -static \
	-z max-page-size=0x1000 \
	--gc-sections \
	-T SynxKernel-x86_64.lds

# ================= 文件收集 =================
override CXXFILES    := $(wildcard src/*.cpp) $(wildcard mem/*.cpp)
override CXXOBJECTS  := $(patsubst %.cpp, build/obj/%.o, $(CXXFILES))
override HEADER_DEPS := $(patsubst %.cpp, build/obj/%.d, $(CXXFILES))

# 将 kallsyms.o 单独拎出来，防止被误伤
KALLSYMS_OBJ := build/obj/src/kallsyms/kallsyms.o
OTHER_OBJECTS := $(filter-out $(KALLSYMS_OBJ), $(CXXOBJECTS))

-include $(HEADER_DEPS)

# ================= 构建规则 =================

# 1. 通用 C++ 编译规则
build/obj/src/%.o: src/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/src/kallsyms/%.o: src/kallsyms/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

build/obj/mem/%.o: mem/%.cpp
	@mkdir -p "$(dir $@)"
	@echo "  CXX     $<"
	$(Q)$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

# 3. 从临时 ELF 提取排序后的函数符号
build/bin/symtab.txt: build/bin/sxImage_temp.elf
	@echo "  NM      Extracting sorted symbols"
	$(Q)nm -n --defined-only $< | grep -E ' [Tt] ' > $@

# 4. 将符号表转换为 C++ 数组
build/bin/symtab_gen.cpp: build/bin/symtab.txt
	@echo "  GEN     Generating kallsyms array"
	@echo "// Auto-generated by Makefile" > $@
	@echo "#include <stdint.h>" >> $@
	@echo "struct KSym { uint64_t addr; const char* name; };" >> $@
	@echo "extern \"C\" const KSym kallsyms_syms[] = {" >> $@
	@awk '{printf "    {0x%s, \"%s\"},\n", $$1, $$3}' $< >> $@
	@echo "    {0, nullptr}" >> $@
	@echo "};" >> $@
	@echo "extern \"C\" const uint64_t kallsyms_syms_count = $(shell wc -l < $<);" >> $@

build/bin/sxImage_temp.elf: $(OTHER_OBJECTS) build/obj/src/kallsyms/kallsyms_stub.o SynxKernel-x86_64.lds
	@mkdir -p "$(dir $@)"
	@echo "  LD      [Temp] $@"
	$(LD) $(LDFLAGS) $(OTHER_OBJECTS) build/obj/src/kallsyms/kallsyms_stub.o -o $@

# 3. 【阶段二】从临时 ELF 中提取符号表
build/bin/symtab.bin build/bin/strtab.bin: build/bin/sxImage_temp.elf
	@echo "  OBJCOPY Extracting symbols"
	$(OBJCOPY) -j .symtab -O binary $< build/bin/symtab.bin
	$(OBJCOPY) -j .strtab -O binary $< build/bin/strtab.bin

# 4. 【阶段二】将二进制文件打包为标准 ELF 目标文件
# 这一步会生成包含 _binary_build_bin_symtab_bin_start 等符号的标准 .o 文件
build/bin/symtab.o: build/bin/symtab.bin
	@echo "  LD      [Binary] symtab.o"
	$(LD) -r -b binary -o $@ $<

# 5. 【阶段三】编译生成的符号表
build/obj/build/bin/symtab_gen.o: build/bin/symtab_gen.cpp
	@mkdir -p "$(dir $@)"
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

# 6. 最终链接
build/bin/$(OUTPUT): $(OTHER_OBJECTS) $(KALLSYMS_OBJ) build/obj/build/bin/symtab_gen.o SynxKernel-x86_64.lds
	@mkdir -p "$(dir $@)"
	@echo "  LD      [Final] $@"
	$(LD) $(LDFLAGS) $(OTHER_OBJECTS) $(KALLSYMS_OBJ) build/obj/build/bin/symtab_gen.o -o $@

# ================= 镜像与运行 =================
.PHONY: kernel
kernel: build/bin/$(OUTPUT)

.PHONY: bootloader
bootloader: 
	make -C assets/limine-bootloader all

$(IMAGE_NAME).iso: kernel bootloader
	mkdir -p build/iso_root/boot
	cp -v build/bin/$(OUTPUT) build/iso_root/boot/
	mkdir -p build/iso_root/boot/limine
	cp -v limine.conf assets/limine-bootloader/limine-bios.sys assets/limine-bootloader/limine-bios-cd.bin assets/limine-bootloader/limine-uefi-cd.bin build/iso_root/boot/limine/
	mkdir -p build/iso_root/EFI/BOOT
	cp -v assets/limine-bootloader/BOOTX64.EFI build/iso_root/EFI/BOOT/
	cp -v assets/limine-bootloader/BOOTIA32.EFI build/iso_root/EFI/BOOT/
	xorriso -as mkisofs -R -r -J -b boot/limine/limine-bios-cd.bin \
		-no-emul-boot -boot-load-size 4 -boot-info-table -hfsplus \
		-apm-block-size 2048 --efi-boot boot/limine/limine-uefi-cd.bin \
		-efi-boot-part --efi-boot-image --protective-msdos-label \
		build/iso_root -o $(IMAGE_NAME).iso
	./assets/limine-bootloader/limine bios-install $(IMAGE_NAME).iso

.PHONY: all
all: $(IMAGE_NAME).iso

.PHONY: run
run: all
	qemu-system-x86_64 \
		-M q35 \
		-cdrom $(IMAGE_NAME).iso \
		-boot d \
		-d int,cpu_reset \
		-no-reboot \
		$(QEMUFLAGS)

.PHONY: clean
clean:
	rm -rf build
	make -C assets/limine-bootloader clean